spring:
  application:
    name: serviceb

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "info,health"

#ambas requisições têm o mesmo efeito...
#curl http://localhost:8082/helloEureka

#esta foi retirada de: http://localhost:8761/eureka/
#curl http://host.docker.internal:8082/helloEureka
